name: test_brik
description: Aplikasi quran mobile
publish_to: "none"

version: 1.1.1+13

environment:
  sdk: ">=2.19.6 <3.2.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3
  connectivity_plus: ^4.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  get_it: ^7.6.0
  injectable: ^2.1.1
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  easy_localization: ^3.0.2
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  oktoast: ^3.3.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^7.1.0
  formz: ^0.6.1
  carousel_slider: ^4.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.6
  injectable_generator:
  freezed: ^2.4.0
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
          weight: 300
          style: italic

